### ISSUE TITLE
Persisting storage issue

### ISSUE THREAD

**Issue by stoltzmaniac** [stoltzmaniac/foco_ds_portal#15]
Any ideas @tompropst about why I can't get `web-db` to work as a volume?

After I add the `volumes` section:
```
web-db:
    container_name: web-db
    build:
      context: ./project/server/db
      dockerfile: Dockerfile
    ports:
      - 5435:5432
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - ./backup_data/postgres:/var/lib/postgresql/data
```

I get an error:

```
Waiting for postgres...
web-db: forward host lookup failed: Unknown host
web-db: forward host lookup failed: Unknown host
....goes on like this...
```

Any ideas?
